Repository ovh-ux/manager-webpack-config, pull requests merged in 2018-11, with the labels that each got.

#40 build(deps): bump component-rollup-config to v2.1.3
  yarn.lock
Labels: bug

#42 Package files entry
  package.json
Labels: bug, enhancement

#44 fix(deps): upgrade component-rollup-config to v2.1.5
  yarn.lock
Labels: bug

#45 fix(plugin): add filtering option
  src/loaders/translation-inject.js
  src/loaders/translation-ui-router.js
  src/webpack.common.js
Labels: bug

#46 docs(readme.example): specify chunkhash on output.filename property
  README.md
Labels: enhancement

#47 feat(webpackbar): bump to v3.2.1 and add some options
  package.json
  src/webpack.common.js
  yarn.lock
Labels: enhancement

#48 fix(deps): upgrade component-rollup-config to v3.0.1
  package.json
  yarn.lock
Labels: bug
