Repository ovh-ux/manager-webpack-config, pull requests merged in 2018-10, with the labels that each got.

#12 docs(contributing): referring to the correct eslint config url
  CONTRIBUTING.md
Labels: enhancement

#13 style(editorconfig): update rules
  .editorconfig
Labels: enhancement

#14 build: add css rule
  webpack.common.js
Labels: enhancement

#16 fix: add missing deps
  package.json
  yarn.lock
Labels: bug

#17 docs(contributing): update file and fix some sentences
  CONTRIBUTING.md
Labels: bug, enhancement

#18 docs: enhance community profile (code of conduct and issue templates)
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#19 fix(commitlint): move config file to .commitlintrc.js
  .commitlintrc.js
Labels: enhancement

#21 fix(dev): remove deprecated logLevel option
  webpack.dev.js
Labels: bug

#23 style(eslint): apply correct indentation
  .eslintrc
Labels: enhancement

#26 fix(dependencies): move husky to dev dependencies
  package.json
Labels: bug

#22 fix: remove .npmrc file
  .npmrc
Labels: bug

#24 style(gitattributes): add gitattributes file
  .gitattributes
Labels: enhancement

#28 fix(package.json): update keywords list
  package.json
Labels: bug

#27 Generate CHANGELOG.md
  CHANGELOG.md
  package.json
Labels: enhancement

#29 fix(resolve): add modules resolve path
  webpack.common.js
Labels: bug

#30 refactor: extract configuration from package.json into json files
  .huskyrc.json
  .lintstagedrc.json
  package.json
Labels: enhancement

#31 build(deps): bump manager-webpack-dev-server to v2.0.1
  yarn.lock
Labels: enhancement

#32 fix(deps): bump manager-webpack-dev-server to v2.0.2
  yarn.lock
Labels: bug

#33 docs(readme): update readme.md file
  README.md
Labels: enhancement

#35 build(deps): upgrade webpack from v4.20.2 to v4.23.1
  yarn.lock
Labels: enhancement

#34 refactor: move code to src folder
  package.json
  src/index.js
  src/loaders/translations.js
  src/loaders/ui-router-translations.js
  src/webpack.common.js
  src/webpack.prod.js
Labels: enhancement

#36 Feat/rollup plugins
  package.json
  src/loaders/translation-inject.js
  src/loaders/translation-ui-router.js
  src/loaders/translation-xml.js
  src/webpack.common.js
  yarn.lock
Labels: enhancement

#37 fix: remove dead code
  src/loaders/translations.js
  src/loaders/ui-router-translations.js
Labels: enhancement

#38 build: upgrade component-rollup-config to 2.1.1
  package.json
  yarn.lock
Labels: bug

#39 Fix/rollup plugins
  package.json
  src/loaders/translation-inject.js
  src/loaders/translation-ui-router.js
  src/loaders/translation-xml.js
  yarn.lock
Labels: bug
